version: '3'
services:
  db:
    image: postgres:10-alpine
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c 'rm -f tmp/pids/server.pid && rails s -b 0.0.0.0'
    volumes:
      - .:/todo_dup
      - bundle:/usr/local/bundle
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: postgres
      DB_NAME: todo_dup
      DB_PASSWORD: password
      DB_HOST: db
    tty: true
    stdin_open: true
volumes:
  bundle:
    driver: local
